Repository Team-Carea/Carea-Flutter, pull requests merged in 2024-02, with the labels that each got.

#6 1:1 채팅방 UI, 웹소켓
  carea/android/app/build.gradle
  carea/lib/app/common/const/app_colors.dart
  carea/lib/app/common/const/config.dart
  carea/lib/app/common/layout/default_layout.dart
  carea/lib/app/data/models/chat_list_model.dart
  carea/lib/app/data/services/chat_room_service.dart
  carea/lib/app/modules/chat/controller/chat_controller.dart
  carea/lib/app/modules/chat/view/chat_list_screen.dart
  carea/lib/app/modules/chat/view/chat_room_screen.dart
  carea/lib/app/modules/confirm_help/view/confirm_help_screen.dart
  carea/pubspec.yaml
Labels: 🔨feat, 🎨design

#7 커뮤니티 UI, 마이페이지 UI
  carea/asset/svg/icon/Group 33.png
  carea/lib/app/common/component/board_button.dart
  carea/lib/app/common/component/bottom_bar.dart
  carea/lib/app/common/component/category.dart
  carea/lib/app/common/component/progress_bar.dart
  carea/lib/app/modules/chat/view/chat_list_screen.dart
  carea/lib/app/modules/community/controller/community_controller.dart
  carea/lib/app/modules/community/view/community_screen.dart
  carea/lib/app/modules/community/view/create_post_screen.dart
  carea/lib/app/modules/community/view/post_detail_screen.dart
  carea/lib/app/modules/community/view/post_list_screen.dart
  carea/lib/app/modules/nearhelp/view/nearhelp_screen.dart
  carea/lib/app/modules/user/view/mypage_screen.dart
  carea/lib/app/routes/app_routes.dart
  carea/pubspec.lock
  carea/pubspec.yaml
Labels: 🔨feat, 🎨design

#15 도움 찾기 UI
  carea/lib/app/common/component/toast_popup.dart
  carea/lib/app/modules/nearhelp/controller/google_map_controller.dart
  carea/lib/app/modules/nearhelp/controller/nearhelp_controller.dart
  carea/lib/app/modules/nearhelp/view/check_near_screen.dart
  carea/lib/app/modules/nearhelp/view/nearhelp_screen.dart
  carea/pubspec.yaml
Labels: 🔨feat, 📬 api, 🎨design

#28 도움찾기 API
  carea/android/app/src/main/AndroidManifest.xml
  carea/android/build.gradle
  carea/asset/img/redpin.png
  carea/asset/svg/icon/Group 33.png
  carea/asset/svg/icon/default.svg
  carea/lib/app/common/component/progress_bar.dart
  carea/lib/app/modules/nearhelp/controller/google_map_controller.dart
  carea/lib/app/modules/nearhelp/view/address_search_screen.dart
  carea/lib/app/modules/nearhelp/view/check_near_screen.dart
  carea/lib/app/modules/nearhelp/view/nearhelp_screen.dart
  carea/lib/app/modules/user/view/mypage_screen.dart
  carea/pubspec.yaml
Labels: 🔨feat, 📬 api

#37 커뮤니티 API
  carea/android/app/build.gradle
  carea/lib/app/common/component/board_button.dart
  carea/lib/app/data/models/comment_model.dart
  carea/lib/app/data/models/post_model.dart
  carea/lib/app/modules/community/controller/community_comments_controller.dart
  carea/lib/app/modules/community/controller/community_controller.dart
  carea/lib/app/modules/community/view/community_screen.dart
  carea/lib/app/modules/community/view/create_post_screen.dart
  carea/lib/app/modules/community/view/post_detail_screen.dart
  carea/lib/app/modules/community/view/post_list_screen.dart
  carea/lib/app/modules/nearhelp/controller/google_map_controller.dart
  carea/lib/app/modules/user/view/mypage_screen.dart
  carea/lib/main.dart
Labels: 🔧fix, 📬 api, 🎨design

#40 채팅기능 관련 UI 오류 해결
  carea/lib/app/common/layout/default_layout.dart
  carea/lib/app/modules/chat/view/chat_room_screen.dart
Labels: 🔧fix

#41 댓글 출력 API
  carea/lib/app/data/models/comment_model.dart
  carea/lib/app/modules/community/controller/community_comments_controller.dart
  carea/lib/app/modules/community/view/post_detail_screen.dart
  carea/pubspec.yaml
Labels: 🔧fix, 📬 api

#42 온보딩 화면
  carea/asset/img/fifth.png
  carea/asset/img/first.png
  carea/asset/img/fourth.png
  carea/asset/img/second.png
  carea/asset/img/sixth.png
  carea/asset/img/third.png
  carea/lib/app/modules/user/view/onboarding_screen.dart
  carea/lib/main.dart
  carea/pubspec.yaml
Labels: 🔨feat, 🎨design
